from selenium import webdriver
from selenium.webdriver import Keys
from selenium.webdriver.common.by import By
import time
from selenium.webdriver.chrome.options import Options #as chrome_options
from fake_useragent import UserAgent
from selenium.common.exceptions import NoSuchElementException
from driver import driver

STAGE_URL = 'https://stage.xnl.zpoken.io/login'
DEV_URL = 'https://dev.xnl.zpoken.io/login'
URL = 'https://stage.xnl.zpoken.io/login'
USER_WITH_EMAIL_VERIFICATION = 'chronicletest110@gmail.com'
USER_WITH_EMAIL_AND_KYC_VERIFICATION = 'chronicletest5@ukr.net'


def test_top_up_usdc_use_valid_data_with_fiat():
    browser = driver
    browser.get(URL)
    input_chronicle_login = browser.find_element_by_xpath('//input[@name="login"]')
    input_chronicle_login.send_keys(USER_WITH_EMAIL_AND_KYC_VERIFICATION)
    time.sleep(1)
    input_chronicle_password = browser.find_element_by_xpath('//input[@name="password"]')
    input_chronicle_password.send_keys("213456qaZ")
    time.sleep(1)
    check_box = browser.find_element_by_xpath(
        "//div[@class='LoginForm_input__ZZfRr LoginForm_checkbox__KEUgt']//label[@class='Input_checkbox__cuH_e']")
    check_box.click()
    time.sleep(2)
    sign_in_button = browser.find_element_by_xpath(
        "//div[@class='LoginForm_button__tiE3C']//button[@type='button']")
    sign_in_button.click()
    time.sleep(3)
    pop_up_two_fa = browser.find_element_by_xpath(
        "//div[@class='Modal_modal__77o1K Modal_center__9TGY8 ']//div[@class='Modal_yellow__0RbLH']//button[@class='Button_btn__JyuE1 Button_transparent__FdLwD Button_withIcon__1TgpF']")
    pop_up_two_fa.click()
    time.sleep(2)
    user_drop = browser.find_element_by_xpath("//div[@class='UserHeaderCard_dropdownBtn__eXCOo']").click()
    time.sleep(1)
    manage_button = browser.find_element_by_xpath("//button[@class='Button_btn__JyuE1 Button_violet__5aLbL']").click()
    time.sleep(1)
    balance_before = browser.find_elements_by_xpath("//span[@class='UserHeaderCard_value__zgpGT']")
    bal1 = balance_before[0].text
    print(bal1)

    usdc_drop = browser.find_element_by_id('USDC').click()
    time.sleep(1)
    fiat = browser.find_element_by_id('Top_up_with_fiat').click()
    time.sleep(1)
    sum = 100
    amount = browser.find_element_by_xpath("//input[@name='amount']")
    amount.send_keys(sum)
    card_holder = browser.find_element_by_xpath("//input[@name='ccname']")
    card_holder.send_keys('Name Surname')
    card_number = browser.find_element_by_xpath("//input[@name='cardnumber']")
    card_number.send_keys('4200 0000 0000 0000')
    mm_yy = browser.find_element_by_xpath("//input[@name='expiry']")
    mm_yy.send_keys('1224')
    cvc = browser.find_element_by_xpath("//input[@name='cvc']")
    cvc.send_keys('123')
    country_drop = browser.find_element_by_xpath(
        "//div[@class='CustomSelect_select__5EopE CustomSelect_crypto__mGhH3 CustomSelect_montserrat__L3McY']")
    country_drop.click()
    time.sleep(1)
    country = browser.find_elements_by_xpath("//div[@class='CustomSelect_option__x3Rbv']")
    country[0].click()
    city = browser.find_element_by_xpath("//input[@name='city']")
    city.send_keys('City')
    address_one = browser.find_element_by_xpath("//input[@name='addressLine_1']")
    address_one.send_keys('address one')
    address_two = browser.find_element_by_xpath("//input[@name='addressLine_2']")
    address_two.send_keys('address two')
    province = browser.find_element_by_xpath("//input[@name='district']")
    province.send_keys('district')
    postal = browser.find_element_by_xpath("//input[@name='postalCode']")
    postal.send_keys('58000')
    time.sleep(1)
    deposit_funds = browser.find_element_by_xpath(
        "//button[@class='Button_btn__JyuE1 Button_violet__5aLbL Button_withIcon__1TgpF']")
    deposit_funds.click()
    time.sleep(1)
    top_up = browser.find_element_by_id('Are_you_sure_you_want_to_make_a_top_up__top_up')
    top_up.click()
    time.sleep(10)
    cong = browser.find_element_by_xpath("//p[@class='__3dsecure_smallText__V9LrF']").text
    assert cong == 'Your transaction was successful'
    back_to_store = browser.find_element_by_xpath(
        "//a[@class='Button_btn__JyuE1 Button_violet__5aLbL Button_withIcon__1TgpF']")
    back_to_store.click()
    time.sleep(5)
    balance_after = browser.find_elements_by_xpath("//span[@class='UserHeaderCard_value__zgpGT']")
    bal2 = balance_after[0].text
    # bal3 = int(bal2) - sum
    print(bal1)
    assert float(bal1) == float(bal2) - sum
    time.sleep(5)


def test_top_up_usdc_use_valid_data_with_fiat_check_nevermind_button():
    browser = driver
    browser.get(URL)
    input_chronicle_login = browser.find_element_by_xpath('//input[@name="login"]')
    input_chronicle_login.send_keys(USER_WITH_EMAIL_AND_KYC_VERIFICATION)
    time.sleep(1)
    input_chronicle_password = browser.find_element_by_xpath('//input[@name="password"]')
    input_chronicle_password.send_keys("213456qaZ")
    time.sleep(1)
    check_box = browser.find_element_by_xpath(
        "//div[@class='LoginForm_input__ZZfRr LoginForm_checkbox__KEUgt']//label[@class='Input_checkbox__cuH_e']")
    check_box.click()
    time.sleep(2)
    sign_in_button = browser.find_element_by_xpath(
        "//div[@class='LoginForm_button__tiE3C']//button[@type='button']")
    sign_in_button.click()
    time.sleep(3)
    pop_up_two_fa = browser.find_element_by_xpath(
        "//div[@class='Modal_modal__77o1K Modal_center__9TGY8 ']//div[@class='Modal_yellow__0RbLH']//button[@class='Button_btn__JyuE1 Button_transparent__FdLwD Button_withIcon__1TgpF']")
    pop_up_two_fa.click()
    time.sleep(2)
    user_drop = browser.find_element_by_xpath("//div[@class='UserHeaderCard_dropdownBtn__eXCOo']").click()
    time.sleep(1)
    manage_button = browser.find_element_by_xpath("//button[@class='Button_btn__JyuE1 Button_violet__5aLbL']").click()
    time.sleep(1)
    usdc_drop = browser.find_element_by_id('USDC').click()
    time.sleep(1)
    fiat = browser.find_element_by_id('Top_up_with_fiat').click()
    time.sleep(1)
    amount = browser.find_element_by_xpath("//input[@name='amount']")
    amount.send_keys('100')
    card_holder = browser.find_element_by_xpath("//input[@name='ccname']")
    card_holder.send_keys('Name Surname')
    card_number = browser.find_element_by_xpath("//input[@name='cardnumber']")
    card_number.send_keys('4200 0000 0000 0000')
    mm_yy = browser.find_element_by_xpath("//input[@name='expiry']")
    mm_yy.send_keys('1224')
    cvc = browser.find_element_by_xpath("//input[@name='cvc']")
    cvc.send_keys('123')
    country_drop = browser.find_element_by_xpath("//div[@class='CustomSelect_select__5EopE CustomSelect_crypto__mGhH3 CustomSelect_montserrat__L3McY']")
    country_drop.click()
    time.sleep(1)
    country = browser.find_elements_by_xpath("//div[@class='CustomSelect_option__x3Rbv']")
    country[0].click()
    city = browser.find_element_by_xpath("//input[@name='city']")
    city.send_keys('City')
    address_one = browser.find_element_by_xpath("//input[@name='addressLine_1']")
    address_one.send_keys('address one')
    address_two = browser.find_element_by_xpath("//input[@name='addressLine_2']")
    address_two.send_keys('address two')
    province = browser.find_element_by_xpath("//input[@name='district']")
    province.send_keys('district')
    postal = browser.find_element_by_xpath("//input[@name='postalCode']")
    postal.send_keys('58000')
    time.sleep(1)
    deposit_funds = browser.find_element_by_xpath("//button[@class='Button_btn__JyuE1 Button_violet__5aLbL Button_withIcon__1TgpF']")
    deposit_funds.click()
    time.sleep(1)
    never_mind = browser.find_element_by_id('Are_you_sure_you_want_to_make_a_top_up__nevermind')
    never_mind.click()
    time.sleep(1)
    back_button = browser.find_elements_by_xpath("//button[@class='Button_btn__JyuE1 Button_transparent__FdLwD Button_withIcon__1TgpF']")
    back_button[2].click()
    time.sleep(1)


def test_top_up_usdc_use_valid_data_with_fiat_user_lost_address_line2_empty():
    browser = driver
    browser.get(URL)
    input_chronicle_login = browser.find_element_by_xpath('//input[@name="login"]')
    input_chronicle_login.send_keys(USER_WITH_EMAIL_AND_KYC_VERIFICATION)
    time.sleep(1)
    input_chronicle_password = browser.find_element_by_xpath('//input[@name="password"]')
    input_chronicle_password.send_keys("213456qaZ")
    time.sleep(1)
    check_box = browser.find_element_by_xpath(
        "//div[@class='LoginForm_input__ZZfRr LoginForm_checkbox__KEUgt']//label[@class='Input_checkbox__cuH_e']")
    check_box.click()
    time.sleep(2)
    sign_in_button = browser.find_element_by_xpath(
        "//div[@class='LoginForm_button__tiE3C']//button[@type='button']")
    sign_in_button.click()
    time.sleep(3)
    pop_up_two_fa = browser.find_element_by_xpath(
        "//div[@class='Modal_modal__77o1K Modal_center__9TGY8 ']//div[@class='Modal_yellow__0RbLH']//button[@class='Button_btn__JyuE1 Button_transparent__FdLwD Button_withIcon__1TgpF']")
    pop_up_two_fa.click()
    time.sleep(2)
    user_drop = browser.find_element_by_xpath("//div[@class='UserHeaderCard_dropdownBtn__eXCOo']").click()
    time.sleep(1)
    manage_button = browser.find_element_by_xpath("//button[@class='Button_btn__JyuE1 Button_violet__5aLbL']").click()
    time.sleep(1)
    usdc_drop = browser.find_element_by_id('USDC').click()
    time.sleep(1)
    fiat = browser.find_element_by_id('Top_up_with_fiat').click()
    time.sleep(1)
    amount = browser.find_element_by_xpath("//input[@name='amount']")
    amount.send_keys('100')
    card_holder = browser.find_element_by_xpath("//input[@name='ccname']")
    card_holder.send_keys('Name Surname')
    card_number = browser.find_element_by_xpath("//input[@name='cardnumber']")
    card_number.send_keys('4200 0000 0000 0000')
    mm_yy = browser.find_element_by_xpath("//input[@name='expiry']")
    mm_yy.send_keys('1224')
    cvc = browser.find_element_by_xpath("//input[@name='cvc']")
    cvc.send_keys('123')
    country_drop = browser.find_element_by_xpath("//div[@class='CustomSelect_select__5EopE CustomSelect_crypto__mGhH3 CustomSelect_montserrat__L3McY']")
    country_drop.click()
    time.sleep(1)
    country = browser.find_elements_by_xpath("//div[@class='CustomSelect_option__x3Rbv']")
    country[0].click()
    city = browser.find_element_by_xpath("//input[@name='city']")
    city.send_keys('City')
    address_one = browser.find_element_by_xpath("//input[@name='addressLine_1']")
    address_one.send_keys('address one')
    address_two = browser.find_element_by_xpath("//input[@name='addressLine_2']")
    address_two.send_keys('')
    province = browser.find_element_by_xpath("//input[@name='district']")
    province.send_keys('district')
    postal = browser.find_element_by_xpath("//input[@name='postalCode']")
    postal.send_keys('58000')
    time.sleep(1)
    deposit_funds = browser.find_element_by_xpath("//button[@class='Button_btn__JyuE1 Button_violet__5aLbL Button_withIcon__1TgpF']")
    deposit_funds.click()
    time.sleep(1)
    top_up = browser.find_element_by_id('Are_you_sure_you_want_to_make_a_top_up__top_up')
    top_up.click()
    time.sleep(10)
    cong = browser.find_element_by_xpath("//p[@class='__3dsecure_smallText__V9LrF']").text
    assert cong == 'Your transaction was successful'
    back_to_store = browser.find_element_by_xpath("//a[@class='Button_btn__JyuE1 Button_violet__5aLbL Button_withIcon__1TgpF']")
    back_to_store.click()
    time.sleep(5)


def test_top_up_usdc_use_valid_data_min_deposit_with_fiat():
    browser = driver
    browser.get(URL)
    input_chronicle_login = browser.find_element_by_xpath('//input[@name="login"]')
    input_chronicle_login.send_keys(USER_WITH_EMAIL_AND_KYC_VERIFICATION)
    time.sleep(1)
    input_chronicle_password = browser.find_element_by_xpath('//input[@name="password"]')
    input_chronicle_password.send_keys("213456qaZ")
    time.sleep(1)
    check_box = browser.find_element_by_xpath(
        "//div[@class='LoginForm_input__ZZfRr LoginForm_checkbox__KEUgt']//label[@class='Input_checkbox__cuH_e']")
    check_box.click()
    time.sleep(2)
    sign_in_button = browser.find_element_by_xpath(
        "//div[@class='LoginForm_button__tiE3C']//button[@type='button']")
    sign_in_button.click()
    time.sleep(3)
    pop_up_two_fa = browser.find_element_by_xpath(
        "//div[@class='Modal_modal__77o1K Modal_center__9TGY8 ']//div[@class='Modal_yellow__0RbLH']//button[@class='Button_btn__JyuE1 Button_transparent__FdLwD Button_withIcon__1TgpF']")
    pop_up_two_fa.click()
    time.sleep(2)
    user_drop = browser.find_element_by_xpath("//div[@class='UserHeaderCard_dropdownBtn__eXCOo']").click()
    time.sleep(1)
    manage_button = browser.find_element_by_xpath("//button[@class='Button_btn__JyuE1 Button_violet__5aLbL']").click()
    time.sleep(1)
    usdc_drop = browser.find_element_by_id('USDC').click()
    time.sleep(1)
    fiat = browser.find_element_by_id('Top_up_with_fiat').click()
    time.sleep(1)
    amount = browser.find_element_by_xpath("//input[@name='amount']")
    amount.send_keys('0.80')
    card_holder = browser.find_element_by_xpath("//input[@name='ccname']")
    card_holder.send_keys('Name Surname')
    card_number = browser.find_element_by_xpath("//input[@name='cardnumber']")
    card_number.send_keys('4200 0000 0000 0000')
    mm_yy = browser.find_element_by_xpath("//input[@name='expiry']")
    mm_yy.send_keys('1224')
    cvc = browser.find_element_by_xpath("//input[@name='cvc']")
    cvc.send_keys('123')
    country_drop = browser.find_element_by_xpath("//div[@class='CustomSelect_select__5EopE CustomSelect_crypto__mGhH3 CustomSelect_montserrat__L3McY']")
    country_drop.click()
    time.sleep(1)
    country = browser.find_elements_by_xpath("//div[@class='CustomSelect_option__x3Rbv']")
    country[0].click()
    city = browser.find_element_by_xpath("//input[@name='city']")
    city.send_keys('City')
    address_one = browser.find_element_by_xpath("//input[@name='addressLine_1']")
    address_one.send_keys('address one')
    address_two = browser.find_element_by_xpath("//input[@name='addressLine_2']")
    address_two.send_keys('address two')
    province = browser.find_element_by_xpath("//input[@name='district']")
    province.send_keys('district')
    postal = browser.find_element_by_xpath("//input[@name='postalCode']")
    postal.send_keys('58000')
    time.sleep(1)
    deposit_funds = browser.find_element_by_xpath("//button[@class='Button_btn__JyuE1 Button_violet__5aLbL Button_withIcon__1TgpF']")
    deposit_funds.click()
    time.sleep(1)
    top_up = browser.find_element_by_id('Are_you_sure_you_want_to_make_a_top_up__top_up')
    top_up.click()
    time.sleep(10)
    cong = browser.find_element_by_xpath("//p[@class='__3dsecure_smallText__V9LrF']").text
    assert cong == 'Your transaction was successful'
    back_to_store = browser.find_element_by_xpath("//a[@class='Button_btn__JyuE1 Button_violet__5aLbL Button_withIcon__1TgpF']")
    back_to_store.click()
    time.sleep(5)


def test_top_up_usdc_use_valid_data_max_deposit_with_fiat():
    browser = driver
    browser.get(URL)
    input_chronicle_login = browser.find_element_by_xpath('//input[@name="login"]')
    input_chronicle_login.send_keys(USER_WITH_EMAIL_AND_KYC_VERIFICATION)
    time.sleep(1)
    input_chronicle_password = browser.find_element_by_xpath('//input[@name="password"]')
    input_chronicle_password.send_keys("213456qaZ")
    time.sleep(1)
    check_box = browser.find_element_by_xpath(
        "//div[@class='LoginForm_input__ZZfRr LoginForm_checkbox__KEUgt']//label[@class='Input_checkbox__cuH_e']")
    check_box.click()
    time.sleep(2)
    sign_in_button = browser.find_element_by_xpath(
        "//div[@class='LoginForm_button__tiE3C']//button[@type='button']")
    sign_in_button.click()
    time.sleep(3)
    pop_up_two_fa = browser.find_element_by_xpath(
        "//div[@class='Modal_modal__77o1K Modal_center__9TGY8 ']//div[@class='Modal_yellow__0RbLH']//button[@class='Button_btn__JyuE1 Button_transparent__FdLwD Button_withIcon__1TgpF']")
    pop_up_two_fa.click()
    time.sleep(2)
    user_drop = browser.find_element_by_xpath("//div[@class='UserHeaderCard_dropdownBtn__eXCOo']").click()
    time.sleep(1)
    manage_button = browser.find_element_by_xpath("//button[@class='Button_btn__JyuE1 Button_violet__5aLbL']").click()
    time.sleep(1)
    usdc_drop = browser.find_element_by_id('USDC').click()
    time.sleep(1)
    fiat = browser.find_element_by_id('Top_up_with_fiat').click()
    time.sleep(1)
    amount = browser.find_element_by_xpath("//input[@name='amount']")
    amount.send_keys('3000')
    card_holder = browser.find_element_by_xpath("//input[@name='ccname']")
    card_holder.send_keys('Name Surname')
    card_number = browser.find_element_by_xpath("//input[@name='cardnumber']")
    card_number.send_keys('4200 0000 0000 0000')
    mm_yy = browser.find_element_by_xpath("//input[@name='expiry']")
    mm_yy.send_keys('1224')
    cvc = browser.find_element_by_xpath("//input[@name='cvc']")
    cvc.send_keys('123')
    country_drop = browser.find_element_by_xpath("//div[@class='CustomSelect_select__5EopE CustomSelect_crypto__mGhH3 CustomSelect_montserrat__L3McY']")
    country_drop.click()
    time.sleep(1)
    country = browser.find_elements_by_xpath("//div[@class='CustomSelect_option__x3Rbv']")
    country[0].click()
    city = browser.find_element_by_xpath("//input[@name='city']")
    city.send_keys('City')
    address_one = browser.find_element_by_xpath("//input[@name='addressLine_1']")
    address_one.send_keys('address one')
    address_two = browser.find_element_by_xpath("//input[@name='addressLine_2']")
    address_two.send_keys('address two')
    province = browser.find_element_by_xpath("//input[@name='district']")
    province.send_keys('district')
    postal = browser.find_element_by_xpath("//input[@name='postalCode']")
    postal.send_keys('58000')
    time.sleep(1)
    deposit_funds = browser.find_element_by_xpath("//button[@class='Button_btn__JyuE1 Button_violet__5aLbL Button_withIcon__1TgpF']")
    deposit_funds.click()
    time.sleep(1)
    top_up = browser.find_element_by_id('Are_you_sure_you_want_to_make_a_top_up__top_up')
    top_up.click()
    time.sleep(10)
    cong = browser.find_element_by_xpath("//p[@class='__3dsecure_smallText__V9LrF']").text
    assert cong == 'Your transaction was successful'
    back_to_store = browser.find_element_by_xpath("//a[@class='Button_btn__JyuE1 Button_violet__5aLbL Button_withIcon__1TgpF']")
    back_to_store.click()
    time.sleep(5)


def test_top_up_usdc_use_invalid_data_more_than_max_deposit_with_fiat():
    browser = driver
    browser.get(URL)
    input_chronicle_login = browser.find_element_by_xpath('//input[@name="login"]')
    input_chronicle_login.send_keys(USER_WITH_EMAIL_AND_KYC_VERIFICATION)
    time.sleep(1)
    input_chronicle_password = browser.find_element_by_xpath('//input[@name="password"]')
    input_chronicle_password.send_keys("213456qaZ")
    time.sleep(1)
    check_box = browser.find_element_by_xpath(
        "//div[@class='LoginForm_input__ZZfRr LoginForm_checkbox__KEUgt']//label[@class='Input_checkbox__cuH_e']")
    check_box.click()
    time.sleep(2)
    sign_in_button = browser.find_element_by_xpath(
        "//div[@class='LoginForm_button__tiE3C']//button[@type='button']")
    sign_in_button.click()
    time.sleep(3)
    pop_up_two_fa = browser.find_element_by_xpath(
        "//div[@class='Modal_modal__77o1K Modal_center__9TGY8 ']//div[@class='Modal_yellow__0RbLH']//button[@class='Button_btn__JyuE1 Button_transparent__FdLwD Button_withIcon__1TgpF']")
    pop_up_two_fa.click()
    time.sleep(2)
    user_drop = browser.find_element_by_xpath("//div[@class='UserHeaderCard_dropdownBtn__eXCOo']").click()
    time.sleep(1)
    manage_button = browser.find_element_by_xpath("//button[@class='Button_btn__JyuE1 Button_violet__5aLbL']").click()
    time.sleep(1)
    usdc_drop = browser.find_element_by_id('USDC').click()
    time.sleep(1)
    fiat = browser.find_element_by_id('Top_up_with_fiat').click()
    time.sleep(1)
    amount = browser.find_element_by_xpath("//input[@name='amount']")
    amount.send_keys('3000.01')
    card_holder = browser.find_element_by_xpath("//input[@name='ccname']")
    card_holder.send_keys('Name Surname')
    card_number = browser.find_element_by_xpath("//input[@name='cardnumber']")
    card_number.send_keys('4200 0000 0000 0000')
    mm_yy = browser.find_element_by_xpath("//input[@name='expiry']")
    mm_yy.send_keys('1224')
    cvc = browser.find_element_by_xpath("//input[@name='cvc']")
    cvc.send_keys('123')
    country_drop = browser.find_element_by_xpath("//div[@class='CustomSelect_select__5EopE CustomSelect_crypto__mGhH3 CustomSelect_montserrat__L3McY']")
    country_drop.click()
    time.sleep(1)
    country = browser.find_elements_by_xpath("//div[@class='CustomSelect_option__x3Rbv']")
    country[0].click()
    city = browser.find_element_by_xpath("//input[@name='city']")
    city.send_keys('City')
    address_one = browser.find_element_by_xpath("//input[@name='addressLine_1']")
    address_one.send_keys('address one')
    address_two = browser.find_element_by_xpath("//input[@name='addressLine_2']")
    address_two.send_keys('address two')
    province = browser.find_element_by_xpath("//input[@name='district']")
    province.send_keys('district')
    postal = browser.find_element_by_xpath("//input[@name='postalCode']")
    postal.send_keys('58000')
    time.sleep(1)
    error = browser.find_element_by_xpath("//div[@class='PriceInput_tipError__I0RRi']").text
    assert error == 'Should be 3 000 USDC or less'
    deposit_funds = browser.find_element_by_xpath(
        "//button[@class='Button_btn__JyuE1 Button_violet__5aLbL Button_withIcon__1TgpF Button_disable__0XBGJ']")
    deposit_funds.click()
    assert deposit_funds.is_displayed()
    time.sleep(5)
    browser.close()


def test_top_up_usdc_use_invalid_data_less_than_min_deposit_with_fiat():
    browser = driver
    browser.get(URL)
    input_chronicle_login = browser.find_element_by_xpath('//input[@name="login"]')
    input_chronicle_login.send_keys(USER_WITH_EMAIL_AND_KYC_VERIFICATION)
    time.sleep(1)
    input_chronicle_password = browser.find_element_by_xpath('//input[@name="password"]')
    input_chronicle_password.send_keys("213456qaZ")
    time.sleep(1)
    check_box = browser.find_element_by_xpath(
        "//div[@class='LoginForm_input__ZZfRr LoginForm_checkbox__KEUgt']//label[@class='Input_checkbox__cuH_e']")
    check_box.click()
    time.sleep(2)
    sign_in_button = browser.find_element_by_xpath(
        "//div[@class='LoginForm_button__tiE3C']//button[@type='button']")
    sign_in_button.click()
    time.sleep(3)
    pop_up_two_fa = browser.find_element_by_xpath(
        "//div[@class='Modal_modal__77o1K Modal_center__9TGY8 ']//div[@class='Modal_yellow__0RbLH']//button[@class='Button_btn__JyuE1 Button_transparent__FdLwD Button_withIcon__1TgpF']")
    pop_up_two_fa.click()
    time.sleep(2)
    user_drop = browser.find_element_by_xpath("//div[@class='UserHeaderCard_dropdownBtn__eXCOo']").click()
    time.sleep(1)
    manage_button = browser.find_element_by_xpath("//button[@class='Button_btn__JyuE1 Button_violet__5aLbL']").click()
    time.sleep(1)
    usdc_drop = browser.find_element_by_id('USDC').click()
    time.sleep(1)
    fiat = browser.find_element_by_id('Top_up_with_fiat').click()
    time.sleep(1)
    amount = browser.find_element_by_xpath("//input[@name='amount']")
    amount.send_keys('0.79')
    card_holder = browser.find_element_by_xpath("//input[@name='ccname']")
    card_holder.send_keys('Name Surname')
    card_number = browser.find_element_by_xpath("//input[@name='cardnumber']")
    card_number.send_keys('4200 0000 0000 0000')
    mm_yy = browser.find_element_by_xpath("//input[@name='expiry']")
    mm_yy.send_keys('1224')
    cvc = browser.find_element_by_xpath("//input[@name='cvc']")
    cvc.send_keys('123')
    country_drop = browser.find_element_by_xpath("//div[@class='CustomSelect_select__5EopE CustomSelect_crypto__mGhH3 CustomSelect_montserrat__L3McY']")
    country_drop.click()
    time.sleep(1)
    country = browser.find_elements_by_xpath("//div[@class='CustomSelect_option__x3Rbv']")
    country[0].click()
    city = browser.find_element_by_xpath("//input[@name='city']")
    city.send_keys('City')
    address_one = browser.find_element_by_xpath("//input[@name='addressLine_1']")
    address_one.send_keys('address one')
    address_two = browser.find_element_by_xpath("//input[@name='addressLine_2']")
    address_two.send_keys('address two')
    province = browser.find_element_by_xpath("//input[@name='district']")
    province.send_keys('district')
    postal = browser.find_element_by_xpath("//input[@name='postalCode']")
    postal.send_keys('58000')
    time.sleep(1)
    error = browser.find_element_by_xpath("//div[@class='PriceInput_tipError__I0RRi']").text
    assert error == 'Should be 0.8 USDC or bigger'
    deposit_funds = browser.find_element_by_xpath(
        "//button[@class='Button_btn__JyuE1 Button_violet__5aLbL Button_withIcon__1TgpF Button_disable__0XBGJ']")
    deposit_funds.click()
    assert deposit_funds.is_displayed()
    time.sleep(1)
    browser.close()


def test_top_up_usdc_use_invalid_data_lost_deposit_field_empty():
    browser = driver
    browser.get(URL)
    input_chronicle_login = browser.find_element_by_xpath('//input[@name="login"]')
    input_chronicle_login.send_keys(USER_WITH_EMAIL_AND_KYC_VERIFICATION)
    time.sleep(1)
    input_chronicle_password = browser.find_element_by_xpath('//input[@name="password"]')
    input_chronicle_password.send_keys("213456qaZ")
    time.sleep(1)
    check_box = browser.find_element_by_xpath(
        "//div[@class='LoginForm_input__ZZfRr LoginForm_checkbox__KEUgt']//label[@class='Input_checkbox__cuH_e']")
    check_box.click()
    time.sleep(2)
    sign_in_button = browser.find_element_by_xpath(
        "//div[@class='LoginForm_button__tiE3C']//button[@type='button']")
    sign_in_button.click()
    time.sleep(3)
    pop_up_two_fa = browser.find_element_by_xpath(
        "//div[@class='Modal_modal__77o1K Modal_center__9TGY8 ']//div[@class='Modal_yellow__0RbLH']//button[@class='Button_btn__JyuE1 Button_transparent__FdLwD Button_withIcon__1TgpF']")
    pop_up_two_fa.click()
    time.sleep(2)
    user_drop = browser.find_element_by_xpath("//div[@class='UserHeaderCard_dropdownBtn__eXCOo']").click()
    time.sleep(1)
    manage_button = browser.find_element_by_xpath("//button[@class='Button_btn__JyuE1 Button_violet__5aLbL']").click()
    time.sleep(1)
    usdc_drop = browser.find_element_by_id('USDC').click()
    time.sleep(1)
    fiat = browser.find_element_by_id('Top_up_with_fiat').click()
    time.sleep(1)
    amount = browser.find_element_by_xpath("//input[@name='amount']")
    amount.send_keys('')
    card_holder = browser.find_element_by_xpath("//input[@name='ccname']")
    card_holder.send_keys('Name Surname')
    card_number = browser.find_element_by_xpath("//input[@name='cardnumber']")
    card_number.send_keys('4200 0000 0000 0000')
    mm_yy = browser.find_element_by_xpath("//input[@name='expiry']")
    mm_yy.send_keys('1224')
    cvc = browser.find_element_by_xpath("//input[@name='cvc']")
    cvc.send_keys('123')
    country_drop = browser.find_element_by_xpath("//div[@class='CustomSelect_select__5EopE CustomSelect_crypto__mGhH3 CustomSelect_montserrat__L3McY']")
    country_drop.click()
    time.sleep(1)
    country = browser.find_elements_by_xpath("//div[@class='CustomSelect_option__x3Rbv']")
    country[0].click()
    city = browser.find_element_by_xpath("//input[@name='city']")
    city.send_keys('City')
    address_one = browser.find_element_by_xpath("//input[@name='addressLine_1']")
    address_one.send_keys('address one')
    address_two = browser.find_element_by_xpath("//input[@name='addressLine_2']")
    address_two.send_keys('address two')
    province = browser.find_element_by_xpath("//input[@name='district']")
    province.send_keys('district')
    postal = browser.find_element_by_xpath("//input[@name='postalCode']")
    postal.send_keys('58000')
    time.sleep(1)
    error = browser.find_element_by_xpath("//div[@class='PriceInput_tipError__I0RRi']").text
    assert error == 'Required'
    deposit_funds = browser.find_element_by_xpath(
        "//button[@class='Button_btn__JyuE1 Button_violet__5aLbL Button_withIcon__1TgpF Button_disable__0XBGJ']")
    deposit_funds.click()
    assert deposit_funds.is_displayed()
    time.sleep(1)
    browser.close()


def test_top_up_usdc_use_invalid_data_deposit_field_not_correct():
    browser = driver
    browser.get(URL)
    input_chronicle_login = browser.find_element_by_xpath('//input[@name="login"]')
    input_chronicle_login.send_keys(USER_WITH_EMAIL_AND_KYC_VERIFICATION)
    time.sleep(1)
    input_chronicle_password = browser.find_element_by_xpath('//input[@name="password"]')
    input_chronicle_password.send_keys("213456qaZ")
    time.sleep(1)
    check_box = browser.find_element_by_xpath(
        "//div[@class='LoginForm_input__ZZfRr LoginForm_checkbox__KEUgt']//label[@class='Input_checkbox__cuH_e']")
    check_box.click()
    time.sleep(2)
    sign_in_button = browser.find_element_by_xpath(
        "//div[@class='LoginForm_button__tiE3C']//button[@type='button']")
    sign_in_button.click()
    time.sleep(3)
    pop_up_two_fa = browser.find_element_by_xpath(
        "//div[@class='Modal_modal__77o1K Modal_center__9TGY8 ']//div[@class='Modal_yellow__0RbLH']//button[@class='Button_btn__JyuE1 Button_transparent__FdLwD Button_withIcon__1TgpF']")
    pop_up_two_fa.click()
    time.sleep(2)
    user_drop = browser.find_element_by_xpath("//div[@class='UserHeaderCard_dropdownBtn__eXCOo']").click()
    time.sleep(1)
    manage_button = browser.find_element_by_xpath("//button[@class='Button_btn__JyuE1 Button_violet__5aLbL']").click()
    time.sleep(1)
    usdc_drop = browser.find_element_by_id('USDC').click()
    time.sleep(1)
    fiat = browser.find_element_by_id('Top_up_with_fiat').click()
    time.sleep(1)
    amount = browser.find_element_by_xpath("//input[@name='amount']")
    amount.send_keys('-10')
    amount.get_property('value')
    print(amount.get_property('value'))
    assert amount.get_property('value') == '10'
    time.sleep(1)


def test_top_up_usdc_use_invalid_data_deposit_field_using_symbols():
    browser = driver
    browser.get(URL)
    input_chronicle_login = browser.find_element_by_xpath('//input[@name="login"]')
    input_chronicle_login.send_keys(USER_WITH_EMAIL_AND_KYC_VERIFICATION)
    time.sleep(1)
    input_chronicle_password = browser.find_element_by_xpath('//input[@name="password"]')
    input_chronicle_password.send_keys("213456qaZ")
    time.sleep(1)
    check_box = browser.find_element_by_xpath(
        "//div[@class='LoginForm_input__ZZfRr LoginForm_checkbox__KEUgt']//label[@class='Input_checkbox__cuH_e']")
    check_box.click()
    time.sleep(2)
    sign_in_button = browser.find_element_by_xpath(
        "//div[@class='LoginForm_button__tiE3C']//button[@type='button']")
    sign_in_button.click()
    time.sleep(3)
    pop_up_two_fa = browser.find_element_by_xpath(
        "//div[@class='Modal_modal__77o1K Modal_center__9TGY8 ']//div[@class='Modal_yellow__0RbLH']//button[@class='Button_btn__JyuE1 Button_transparent__FdLwD Button_withIcon__1TgpF']")
    pop_up_two_fa.click()
    time.sleep(2)
    user_drop = browser.find_element_by_xpath("//div[@class='UserHeaderCard_dropdownBtn__eXCOo']").click()
    time.sleep(1)
    manage_button = browser.find_element_by_xpath("//button[@class='Button_btn__JyuE1 Button_violet__5aLbL']").click()
    time.sleep(1)
    usdc_drop = browser.find_element_by_id('USDC').click()
    time.sleep(1)
    fiat = browser.find_element_by_id('Top_up_with_fiat').click()
    time.sleep(1)
    amount = browser.find_element_by_xpath("//input[@name='amount']")
    amount.send_keys('qwerty')
    amount.get_property('value')
    print(amount.get_property('value'))
    assert amount.get_property('value') == ''
    time.sleep(1)


def test_top_up_usdc_use_invalid_data_lost_card_holder_field_empty():
    browser = driver
    browser.get(URL)
    input_chronicle_login = browser.find_element_by_xpath('//input[@name="login"]')
    input_chronicle_login.send_keys(USER_WITH_EMAIL_AND_KYC_VERIFICATION)
    time.sleep(1)
    input_chronicle_password = browser.find_element_by_xpath('//input[@name="password"]')
    input_chronicle_password.send_keys("213456qaZ")
    time.sleep(1)
    check_box = browser.find_element_by_xpath(
        "//div[@class='LoginForm_input__ZZfRr LoginForm_checkbox__KEUgt']//label[@class='Input_checkbox__cuH_e']")
    check_box.click()
    time.sleep(2)
    sign_in_button = browser.find_element_by_xpath(
        "//div[@class='LoginForm_button__tiE3C']//button[@type='button']")
    sign_in_button.click()
    time.sleep(3)
    pop_up_two_fa = browser.find_element_by_xpath(
        "//div[@class='Modal_modal__77o1K Modal_center__9TGY8 ']//div[@class='Modal_yellow__0RbLH']//button[@class='Button_btn__JyuE1 Button_transparent__FdLwD Button_withIcon__1TgpF']")
    pop_up_two_fa.click()
    time.sleep(2)
    user_drop = browser.find_element_by_xpath("//div[@class='UserHeaderCard_dropdownBtn__eXCOo']").click()
    time.sleep(1)
    manage_button = browser.find_element_by_xpath("//button[@class='Button_btn__JyuE1 Button_violet__5aLbL']").click()
    time.sleep(1)
    usdc_drop = browser.find_element_by_id('USDC').click()
    time.sleep(1)
    fiat = browser.find_element_by_id('Top_up_with_fiat').click()
    time.sleep(1)
    amount = browser.find_element_by_xpath("//input[@name='amount']")
    amount.send_keys('100')
    card_holder = browser.find_element_by_xpath("//input[@name='ccname']")
    card_holder.send_keys('')
    card_number = browser.find_element_by_xpath("//input[@name='cardnumber']")
    card_number.send_keys('4200 0000 0000 0000')
    mm_yy = browser.find_element_by_xpath("//input[@name='expiry']")
    mm_yy.send_keys('1224')
    cvc = browser.find_element_by_xpath("//input[@name='cvc']")
    cvc.send_keys('123')
    country_drop = browser.find_element_by_xpath("//div[@class='CustomSelect_select__5EopE CustomSelect_crypto__mGhH3 CustomSelect_montserrat__L3McY']")
    country_drop.click()
    time.sleep(1)
    country = browser.find_elements_by_xpath("//div[@class='CustomSelect_option__x3Rbv']")
    country[0].click()
    city = browser.find_element_by_xpath("//input[@name='city']")
    city.send_keys('City')
    address_one = browser.find_element_by_xpath("//input[@name='addressLine_1']")
    address_one.send_keys('address one')
    address_two = browser.find_element_by_xpath("//input[@name='addressLine_2']")
    address_two.send_keys('address two')
    province = browser.find_element_by_xpath("//input[@name='district']")
    province.send_keys('district')
    postal = browser.find_element_by_xpath("//input[@name='postalCode']")
    postal.send_keys('58000')
    time.sleep(1)
    error = browser.find_element_by_xpath("//div[@class='Input_tipError__CKiEf']").text
    assert error == 'Required'
    deposit_funds = browser.find_element_by_xpath(
        "//button[@class='Button_btn__JyuE1 Button_violet__5aLbL Button_withIcon__1TgpF Button_disable__0XBGJ']")
    deposit_funds.click()
    assert deposit_funds.is_displayed()
    time.sleep(1)
    browser.close()


def test_top_up_usdc_use_invalid_data_lost_card_number_field_empty():
    browser = driver
    browser.get(URL)
    input_chronicle_login = browser.find_element_by_xpath('//input[@name="login"]')
    input_chronicle_login.send_keys(USER_WITH_EMAIL_AND_KYC_VERIFICATION)
    time.sleep(1)
    input_chronicle_password = browser.find_element_by_xpath('//input[@name="password"]')
    input_chronicle_password.send_keys("213456qaZ")
    time.sleep(1)
    check_box = browser.find_element_by_xpath(
        "//div[@class='LoginForm_input__ZZfRr LoginForm_checkbox__KEUgt']//label[@class='Input_checkbox__cuH_e']")
    check_box.click()
    time.sleep(2)
    sign_in_button = browser.find_element_by_xpath(
        "//div[@class='LoginForm_button__tiE3C']//button[@type='button']")
    sign_in_button.click()
    time.sleep(3)
    pop_up_two_fa = browser.find_element_by_xpath(
        "//div[@class='Modal_modal__77o1K Modal_center__9TGY8 ']//div[@class='Modal_yellow__0RbLH']//button[@class='Button_btn__JyuE1 Button_transparent__FdLwD Button_withIcon__1TgpF']")
    pop_up_two_fa.click()
    time.sleep(2)
    user_drop = browser.find_element_by_xpath("//div[@class='UserHeaderCard_dropdownBtn__eXCOo']").click()
    time.sleep(1)
    manage_button = browser.find_element_by_xpath("//button[@class='Button_btn__JyuE1 Button_violet__5aLbL']").click()
    time.sleep(1)
    usdc_drop = browser.find_element_by_id('USDC').click()
    time.sleep(1)
    fiat = browser.find_element_by_id('Top_up_with_fiat').click()
    time.sleep(1)
    amount = browser.find_element_by_xpath("//input[@name='amount']")
    amount.send_keys('100')
    card_holder = browser.find_element_by_xpath("//input[@name='ccname']")
    card_holder.send_keys('clark kent')
    card_number = browser.find_element_by_xpath("//input[@name='cardnumber']")
    card_number.send_keys('')
    mm_yy = browser.find_element_by_xpath("//input[@name='expiry']")
    mm_yy.send_keys('1224')
    cvc = browser.find_element_by_xpath("//input[@name='cvc']")
    cvc.send_keys('123')
    country_drop = browser.find_element_by_xpath("//div[@class='CustomSelect_select__5EopE CustomSelect_crypto__mGhH3 CustomSelect_montserrat__L3McY']")
    country_drop.click()
    time.sleep(1)
    country = browser.find_elements_by_xpath("//div[@class='CustomSelect_option__x3Rbv']")
    country[0].click()
    city = browser.find_element_by_xpath("//input[@name='city']")
    city.send_keys('City')
    address_one = browser.find_element_by_xpath("//input[@name='addressLine_1']")
    address_one.send_keys('address one')
    address_two = browser.find_element_by_xpath("//input[@name='addressLine_2']")
    address_two.send_keys('address two')
    province = browser.find_element_by_xpath("//input[@name='district']")
    province.send_keys('district')
    postal = browser.find_element_by_xpath("//input[@name='postalCode']")
    postal.send_keys('58000')
    time.sleep(1)
    #error = browser.find_element_by_xpath("//div[@class='Input_tipError__CKiEf']").text
    #assert error == 'Required'
    deposit_funds = browser.find_element_by_xpath(
        "//button[@class='Button_btn__JyuE1 Button_violet__5aLbL Button_withIcon__1TgpF Button_disable__0XBGJ']")
    deposit_funds.click()
    assert deposit_funds.is_displayed()
    time.sleep(1)
    browser.close()


def test_top_up_usdc_use_invalid_data_fill_card_number_field_not_full():
    browser = driver
    browser.get(URL)
    input_chronicle_login = browser.find_element_by_xpath('//input[@name="login"]')
    input_chronicle_login.send_keys(USER_WITH_EMAIL_AND_KYC_VERIFICATION)
    time.sleep(1)
    input_chronicle_password = browser.find_element_by_xpath('//input[@name="password"]')
    input_chronicle_password.send_keys("213456qaZ")
    time.sleep(1)
    check_box = browser.find_element_by_xpath(
        "//div[@class='LoginForm_input__ZZfRr LoginForm_checkbox__KEUgt']//label[@class='Input_checkbox__cuH_e']")
    check_box.click()
    time.sleep(2)
    sign_in_button = browser.find_element_by_xpath(
        "//div[@class='LoginForm_button__tiE3C']//button[@type='button']")
    sign_in_button.click()
    time.sleep(3)
    pop_up_two_fa = browser.find_element_by_xpath(
        "//div[@class='Modal_modal__77o1K Modal_center__9TGY8 ']//div[@class='Modal_yellow__0RbLH']//button[@class='Button_btn__JyuE1 Button_transparent__FdLwD Button_withIcon__1TgpF']")
    pop_up_two_fa.click()
    time.sleep(2)
    user_drop = browser.find_element_by_xpath("//div[@class='UserHeaderCard_dropdownBtn__eXCOo']").click()
    time.sleep(1)
    manage_button = browser.find_element_by_xpath("//button[@class='Button_btn__JyuE1 Button_violet__5aLbL']").click()
    time.sleep(1)
    usdc_drop = browser.find_element_by_id('USDC').click()
    time.sleep(1)
    fiat = browser.find_element_by_id('Top_up_with_fiat').click()
    time.sleep(1)
    amount = browser.find_element_by_xpath("//input[@name='amount']")
    amount.send_keys('100')
    card_holder = browser.find_element_by_xpath("//input[@name='ccname']")
    card_holder.send_keys('clark kent')
    card_number = browser.find_element_by_xpath("//input[@name='cardnumber']")
    card_number.send_keys('420000000000000')
    mm_yy = browser.find_element_by_xpath("//input[@name='expiry']")
    mm_yy.send_keys('1224')
    cvc = browser.find_element_by_xpath("//input[@name='cvc']")
    cvc.send_keys('123')
    country_drop = browser.find_element_by_xpath("//div[@class='CustomSelect_select__5EopE CustomSelect_crypto__mGhH3 CustomSelect_montserrat__L3McY']")
    country_drop.click()
    time.sleep(1)
    country = browser.find_elements_by_xpath("//div[@class='CustomSelect_option__x3Rbv']")
    country[0].click()
    city = browser.find_element_by_xpath("//input[@name='city']")
    city.send_keys('City')
    address_one = browser.find_element_by_xpath("//input[@name='addressLine_1']")
    address_one.send_keys('address one')
    address_two = browser.find_element_by_xpath("//input[@name='addressLine_2']")
    address_two.send_keys('address two')
    province = browser.find_element_by_xpath("//input[@name='district']")
    province.send_keys('district')
    postal = browser.find_element_by_xpath("//input[@name='postalCode']")
    postal.send_keys('58000')
    time.sleep(1)
    #error = browser.find_element_by_xpath("//div[@class='Input_tipError__CKiEf']").text
    #assert error == 'Required'
    deposit_funds = browser.find_element_by_xpath(
        "//button[@class='Button_btn__JyuE1 Button_violet__5aLbL Button_withIcon__1TgpF Button_disable__0XBGJ']")
    deposit_funds.click()
    assert deposit_funds.is_displayed()
    time.sleep(1)
    browser.close()


def test_top_up_usdc_use_invalid_data_card_number_field_using_symbols():
    browser = driver
    browser.get(URL)
    input_chronicle_login = browser.find_element_by_xpath('//input[@name="login"]')
    input_chronicle_login.send_keys(USER_WITH_EMAIL_AND_KYC_VERIFICATION)
    time.sleep(1)
    input_chronicle_password = browser.find_element_by_xpath('//input[@name="password"]')
    input_chronicle_password.send_keys("213456qaZ")
    time.sleep(1)
    check_box = browser.find_element_by_xpath(
        "//div[@class='LoginForm_input__ZZfRr LoginForm_checkbox__KEUgt']//label[@class='Input_checkbox__cuH_e']")
    check_box.click()
    time.sleep(2)
    sign_in_button = browser.find_element_by_xpath(
        "//div[@class='LoginForm_button__tiE3C']//button[@type='button']")
    sign_in_button.click()
    time.sleep(3)
    pop_up_two_fa = browser.find_element_by_xpath(
        "//div[@class='Modal_modal__77o1K Modal_center__9TGY8 ']//div[@class='Modal_yellow__0RbLH']//button[@class='Button_btn__JyuE1 Button_transparent__FdLwD Button_withIcon__1TgpF']")
    pop_up_two_fa.click()
    time.sleep(2)
    user_drop = browser.find_element_by_xpath("//div[@class='UserHeaderCard_dropdownBtn__eXCOo']").click()
    time.sleep(1)
    manage_button = browser.find_element_by_xpath("//button[@class='Button_btn__JyuE1 Button_violet__5aLbL']").click()
    time.sleep(1)
    usdc_drop = browser.find_element_by_id('USDC').click()
    time.sleep(1)
    fiat = browser.find_element_by_id('Top_up_with_fiat').click()
    time.sleep(1)
    card_number = browser.find_element_by_xpath("//input[@name='cardnumber']")
    card_number.send_keys('')
    card_number.get_property('value')
    print(card_number.get_property('value'))
    assert card_number.get_property('value') == ''
    time.sleep(1)


def test_top_up_usdc_use_invalid_data_lost_mm_yy_empty():
    browser = driver
    browser.get(URL)
    input_chronicle_login = browser.find_element_by_xpath('//input[@name="login"]')
    input_chronicle_login.send_keys(USER_WITH_EMAIL_AND_KYC_VERIFICATION)
    time.sleep(1)
    input_chronicle_password = browser.find_element_by_xpath('//input[@name="password"]')
    input_chronicle_password.send_keys("213456qaZ")
    time.sleep(1)
    check_box = browser.find_element_by_xpath(
        "//div[@class='LoginForm_input__ZZfRr LoginForm_checkbox__KEUgt']//label[@class='Input_checkbox__cuH_e']")
    check_box.click()
    time.sleep(2)
    sign_in_button = browser.find_element_by_xpath(
        "//div[@class='LoginForm_button__tiE3C']//button[@type='button']")
    sign_in_button.click()
    time.sleep(3)
    pop_up_two_fa = browser.find_element_by_xpath(
        "//div[@class='Modal_modal__77o1K Modal_center__9TGY8 ']//div[@class='Modal_yellow__0RbLH']//button[@class='Button_btn__JyuE1 Button_transparent__FdLwD Button_withIcon__1TgpF']")
    pop_up_two_fa.click()
    time.sleep(2)
    user_drop = browser.find_element_by_xpath("//div[@class='UserHeaderCard_dropdownBtn__eXCOo']").click()
    time.sleep(1)
    manage_button = browser.find_element_by_xpath("//button[@class='Button_btn__JyuE1 Button_violet__5aLbL']").click()
    time.sleep(1)
    usdc_drop = browser.find_element_by_id('USDC').click()
    time.sleep(1)
    fiat = browser.find_element_by_id('Top_up_with_fiat').click()
    time.sleep(1)
    amount = browser.find_element_by_xpath("//input[@name='amount']")
    amount.send_keys('100')
    card_holder = browser.find_element_by_xpath("//input[@name='ccname']")
    card_holder.send_keys('clark kent')
    card_number = browser.find_element_by_xpath("//input[@name='cardnumber']")
    card_number.send_keys('4200000000000000')
    mm_yy = browser.find_element_by_xpath("//input[@name='expiry']")
    mm_yy.send_keys('')
    cvc = browser.find_element_by_xpath("//input[@name='cvc']")
    cvc.send_keys('123')
    country_drop = browser.find_element_by_xpath("//div[@class='CustomSelect_select__5EopE CustomSelect_crypto__mGhH3 CustomSelect_montserrat__L3McY']")
    country_drop.click()
    time.sleep(1)
    country = browser.find_elements_by_xpath("//div[@class='CustomSelect_option__x3Rbv']")
    country[0].click()
    city = browser.find_element_by_xpath("//input[@name='city']")
    city.send_keys('City')
    address_one = browser.find_element_by_xpath("//input[@name='addressLine_1']")
    address_one.send_keys('address one')
    address_two = browser.find_element_by_xpath("//input[@name='addressLine_2']")
    address_two.send_keys('address two')
    province = browser.find_element_by_xpath("//input[@name='district']")
    province.send_keys('district')
    postal = browser.find_element_by_xpath("//input[@name='postalCode']")
    postal.send_keys('58000')
    time.sleep(1)
    #error = browser.find_element_by_xpath("//div[@class='Input_tipError__CKiEf']").text
    #assert error == 'Required'
    deposit_funds = browser.find_element_by_xpath(
        "//button[@class='Button_btn__JyuE1 Button_violet__5aLbL Button_withIcon__1TgpF Button_disable__0XBGJ']")
    deposit_funds.click()
    assert deposit_funds.is_displayed()
    time.sleep(1)
    browser.close()


def test_top_up_usdc_use_invalid_data_fill_mm_yy_field_not_full():
    browser = driver
    browser.get(URL)
    input_chronicle_login = browser.find_element_by_xpath('//input[@name="login"]')
    input_chronicle_login.send_keys(USER_WITH_EMAIL_AND_KYC_VERIFICATION)
    time.sleep(1)
    input_chronicle_password = browser.find_element_by_xpath('//input[@name="password"]')
    input_chronicle_password.send_keys("213456qaZ")
    time.sleep(1)
    check_box = browser.find_element_by_xpath(
        "//div[@class='LoginForm_input__ZZfRr LoginForm_checkbox__KEUgt']//label[@class='Input_checkbox__cuH_e']")
    check_box.click()
    time.sleep(2)
    sign_in_button = browser.find_element_by_xpath(
        "//div[@class='LoginForm_button__tiE3C']//button[@type='button']")
    sign_in_button.click()
    time.sleep(3)
    pop_up_two_fa = browser.find_element_by_xpath(
        "//div[@class='Modal_modal__77o1K Modal_center__9TGY8 ']//div[@class='Modal_yellow__0RbLH']//button[@class='Button_btn__JyuE1 Button_transparent__FdLwD Button_withIcon__1TgpF']")
    pop_up_two_fa.click()
    time.sleep(2)
    user_drop = browser.find_element_by_xpath("//div[@class='UserHeaderCard_dropdownBtn__eXCOo']").click()
    time.sleep(1)
    manage_button = browser.find_element_by_xpath("//button[@class='Button_btn__JyuE1 Button_violet__5aLbL']").click()
    time.sleep(1)
    usdc_drop = browser.find_element_by_id('USDC').click()
    time.sleep(1)
    fiat = browser.find_element_by_id('Top_up_with_fiat').click()
    time.sleep(1)
    amount = browser.find_element_by_xpath("//input[@name='amount']")
    amount.send_keys('100')
    card_holder = browser.find_element_by_xpath("//input[@name='ccname']")
    card_holder.send_keys('clark kent')
    card_number = browser.find_element_by_xpath("//input[@name='cardnumber']")
    card_number.send_keys('4200000000000000')
    mm_yy = browser.find_element_by_xpath("//input[@name='expiry']")
    mm_yy.send_keys('12')
    cvc = browser.find_element_by_xpath("//input[@name='cvc']")
    cvc.send_keys('123')
    country_drop = browser.find_element_by_xpath("//div[@class='CustomSelect_select__5EopE CustomSelect_crypto__mGhH3 CustomSelect_montserrat__L3McY']")
    country_drop.click()
    time.sleep(1)
    country = browser.find_elements_by_xpath("//div[@class='CustomSelect_option__x3Rbv']")
    country[0].click()
    city = browser.find_element_by_xpath("//input[@name='city']")
    city.send_keys('City')
    address_one = browser.find_element_by_xpath("//input[@name='addressLine_1']")
    address_one.send_keys('address one')
    address_two = browser.find_element_by_xpath("//input[@name='addressLine_2']")
    address_two.send_keys('address two')
    province = browser.find_element_by_xpath("//input[@name='district']")
    province.send_keys('district')
    postal = browser.find_element_by_xpath("//input[@name='postalCode']")
    postal.send_keys('58000')
    time.sleep(1)
    #error = browser.find_element_by_xpath("//div[@class='Input_tipError__CKiEf']").text
    #assert error == 'Required'
    deposit_funds = browser.find_element_by_xpath(
        "//button[@class='Button_btn__JyuE1 Button_violet__5aLbL Button_withIcon__1TgpF Button_disable__0XBGJ']")
    deposit_funds.click()
    assert deposit_funds.is_displayed()
    time.sleep(1)
    browser.close()


def test_top_up_usdc_use_invalid_data_mm_yy_field_using_symbols():
    browser = driver
    browser.get(URL)
    input_chronicle_login = browser.find_element_by_xpath('//input[@name="login"]')
    input_chronicle_login.send_keys(USER_WITH_EMAIL_AND_KYC_VERIFICATION)
    time.sleep(1)
    input_chronicle_password = browser.find_element_by_xpath('//input[@name="password"]')
    input_chronicle_password.send_keys("213456qaZ")
    time.sleep(1)
    check_box = browser.find_element_by_xpath(
        "//div[@class='LoginForm_input__ZZfRr LoginForm_checkbox__KEUgt']//label[@class='Input_checkbox__cuH_e']")
    check_box.click()
    time.sleep(2)
    sign_in_button = browser.find_element_by_xpath(
        "//div[@class='LoginForm_button__tiE3C']//button[@type='button']")
    sign_in_button.click()
    time.sleep(3)
    pop_up_two_fa = browser.find_element_by_xpath(
        "//div[@class='Modal_modal__77o1K Modal_center__9TGY8 ']//div[@class='Modal_yellow__0RbLH']//button[@class='Button_btn__JyuE1 Button_transparent__FdLwD Button_withIcon__1TgpF']")
    pop_up_two_fa.click()
    time.sleep(2)
    user_drop = browser.find_element_by_xpath("//div[@class='UserHeaderCard_dropdownBtn__eXCOo']").click()
    time.sleep(1)
    manage_button = browser.find_element_by_xpath("//button[@class='Button_btn__JyuE1 Button_violet__5aLbL']").click()
    time.sleep(1)
    usdc_drop = browser.find_element_by_id('USDC').click()
    time.sleep(1)
    fiat = browser.find_element_by_id('Top_up_with_fiat').click()
    time.sleep(1)
    mm_yy = browser.find_element_by_xpath("//input[@name='expiry']")
    mm_yy.send_keys('qwerty')
    mm_yy.get_property('value')
    print(mm_yy.get_property('value'))
    assert mm_yy.get_property('value') == ''
    time.sleep(1)


def test_top_up_usdc_use_invalid_data_lost_cvc_field_empty():
    browser = driver
    browser.get(URL)
    input_chronicle_login = browser.find_element_by_xpath('//input[@name="login"]')
    input_chronicle_login.send_keys(USER_WITH_EMAIL_AND_KYC_VERIFICATION)
    time.sleep(1)
    input_chronicle_password = browser.find_element_by_xpath('//input[@name="password"]')
    input_chronicle_password.send_keys("213456qaZ")
    time.sleep(1)
    check_box = browser.find_element_by_xpath(
        "//div[@class='LoginForm_input__ZZfRr LoginForm_checkbox__KEUgt']//label[@class='Input_checkbox__cuH_e']")
    check_box.click()
    time.sleep(2)
    sign_in_button = browser.find_element_by_xpath(
        "//div[@class='LoginForm_button__tiE3C']//button[@type='button']")
    sign_in_button.click()
    time.sleep(3)
    pop_up_two_fa = browser.find_element_by_xpath(
        "//div[@class='Modal_modal__77o1K Modal_center__9TGY8 ']//div[@class='Modal_yellow__0RbLH']//button[@class='Button_btn__JyuE1 Button_transparent__FdLwD Button_withIcon__1TgpF']")
    pop_up_two_fa.click()
    time.sleep(2)
    user_drop = browser.find_element_by_xpath("//div[@class='UserHeaderCard_dropdownBtn__eXCOo']").click()
    time.sleep(1)
    manage_button = browser.find_element_by_xpath("//button[@class='Button_btn__JyuE1 Button_violet__5aLbL']").click()
    time.sleep(1)
    usdc_drop = browser.find_element_by_id('USDC').click()
    time.sleep(1)
    fiat = browser.find_element_by_id('Top_up_with_fiat').click()
    time.sleep(1)
    amount = browser.find_element_by_xpath("//input[@name='amount']")
    amount.send_keys('100')
    card_holder = browser.find_element_by_xpath("//input[@name='ccname']")
    card_holder.send_keys('clark kent')
    card_number = browser.find_element_by_xpath("//input[@name='cardnumber']")
    card_number.send_keys('42000000000000000')
    mm_yy = browser.find_element_by_xpath("//input[@name='expiry']")
    mm_yy.send_keys('1224')
    cvc = browser.find_element_by_xpath("//input[@name='cvc']")
    cvc.send_keys('')
    country_drop = browser.find_element_by_xpath("//div[@class='CustomSelect_select__5EopE CustomSelect_crypto__mGhH3 CustomSelect_montserrat__L3McY']")
    country_drop.click()
    time.sleep(1)
    country = browser.find_elements_by_xpath("//div[@class='CustomSelect_option__x3Rbv']")
    country[0].click()
    city = browser.find_element_by_xpath("//input[@name='city']")
    city.send_keys('City')
    address_one = browser.find_element_by_xpath("//input[@name='addressLine_1']")
    address_one.send_keys('address one')
    address_two = browser.find_element_by_xpath("//input[@name='addressLine_2']")
    address_two.send_keys('address two')
    province = browser.find_element_by_xpath("//input[@name='district']")
    province.send_keys('district')
    postal = browser.find_element_by_xpath("//input[@name='postalCode']")
    postal.send_keys('58000')
    time.sleep(1)
    #error = browser.find_element_by_xpath("//div[@class='Input_tipError__CKiEf']").text
    #assert error == 'Required'
    deposit_funds = browser.find_element_by_xpath(
        "//button[@class='Button_btn__JyuE1 Button_violet__5aLbL Button_withIcon__1TgpF Button_disable__0XBGJ']")
    deposit_funds.click()
    assert deposit_funds.is_displayed()
    time.sleep(1)
    browser.close()


def test_top_up_usdc_use_invalid_data_cvc_field_using_symbols():
    browser = driver
    browser.get(URL)
    input_chronicle_login = browser.find_element_by_xpath('//input[@name="login"]')
    input_chronicle_login.send_keys(USER_WITH_EMAIL_AND_KYC_VERIFICATION)
    time.sleep(1)
    input_chronicle_password = browser.find_element_by_xpath('//input[@name="password"]')
    input_chronicle_password.send_keys("213456qaZ")
    time.sleep(1)
    check_box = browser.find_element_by_xpath(
        "//div[@class='LoginForm_input__ZZfRr LoginForm_checkbox__KEUgt']//label[@class='Input_checkbox__cuH_e']")
    check_box.click()
    time.sleep(2)
    sign_in_button = browser.find_element_by_xpath(
        "//div[@class='LoginForm_button__tiE3C']//button[@type='button']")
    sign_in_button.click()
    time.sleep(3)
    pop_up_two_fa = browser.find_element_by_xpath(
        "//div[@class='Modal_modal__77o1K Modal_center__9TGY8 ']//div[@class='Modal_yellow__0RbLH']//button[@class='Button_btn__JyuE1 Button_transparent__FdLwD Button_withIcon__1TgpF']")
    pop_up_two_fa.click()
    time.sleep(2)
    user_drop = browser.find_element_by_xpath("//div[@class='UserHeaderCard_dropdownBtn__eXCOo']").click()
    time.sleep(1)
    manage_button = browser.find_element_by_xpath("//button[@class='Button_btn__JyuE1 Button_violet__5aLbL']").click()
    time.sleep(1)
    usdc_drop = browser.find_element_by_id('USDC').click()
    time.sleep(1)
    fiat = browser.find_element_by_id('Top_up_with_fiat').click()
    time.sleep(1)
    cvc = browser.find_element_by_xpath("//input[@name='cvc']")
    cvc.send_keys('qwerty')
    cvc.get_property('value')
    print(cvc.get_property('value'))
    assert cvc.get_property('value') == ''
    time.sleep(1)


def test_top_up_usdc_use_invalid_data_country_not_selected():
    browser = driver
    browser.get(URL)
    input_chronicle_login = browser.find_element_by_xpath('//input[@name="login"]')
    input_chronicle_login.send_keys(USER_WITH_EMAIL_AND_KYC_VERIFICATION)
    time.sleep(1)
    input_chronicle_password = browser.find_element_by_xpath('//input[@name="password"]')
    input_chronicle_password.send_keys("213456qaZ")
    time.sleep(1)
    check_box = browser.find_element_by_xpath(
        "//div[@class='LoginForm_input__ZZfRr LoginForm_checkbox__KEUgt']//label[@class='Input_checkbox__cuH_e']")
    check_box.click()
    time.sleep(2)
    sign_in_button = browser.find_element_by_xpath(
        "//div[@class='LoginForm_button__tiE3C']//button[@type='button']")
    sign_in_button.click()
    time.sleep(3)
    pop_up_two_fa = browser.find_element_by_xpath(
        "//div[@class='Modal_modal__77o1K Modal_center__9TGY8 ']//div[@class='Modal_yellow__0RbLH']//button[@class='Button_btn__JyuE1 Button_transparent__FdLwD Button_withIcon__1TgpF']")
    pop_up_two_fa.click()
    time.sleep(2)
    user_drop = browser.find_element_by_xpath("//div[@class='UserHeaderCard_dropdownBtn__eXCOo']").click()
    time.sleep(1)
    manage_button = browser.find_element_by_xpath("//button[@class='Button_btn__JyuE1 Button_violet__5aLbL']").click()
    time.sleep(1)
    usdc_drop = browser.find_element_by_id('USDC').click()
    time.sleep(1)
    fiat = browser.find_element_by_id('Top_up_with_fiat').click()
    time.sleep(1)
    amount = browser.find_element_by_xpath("//input[@name='amount']")
    amount.send_keys('100')
    card_holder = browser.find_element_by_xpath("//input[@name='ccname']")
    card_holder.send_keys('clark kent')
    card_number = browser.find_element_by_xpath("//input[@name='cardnumber']")
    card_number.send_keys('42000000000000000')
    mm_yy = browser.find_element_by_xpath("//input[@name='expiry']")
    mm_yy.send_keys('1224')
    cvc = browser.find_element_by_xpath("//input[@name='cvc']")
    cvc.send_keys('123')
    country_drop = browser.find_element_by_xpath("//div[@class='CustomSelect_select__5EopE CustomSelect_crypto__mGhH3 CustomSelect_montserrat__L3McY']")
    country_drop.click()
    city = browser.find_element_by_xpath("//input[@name='city']")
    city.send_keys('City')
    address_one = browser.find_element_by_xpath("//input[@name='addressLine_1']")
    address_one.send_keys('address one')
    address_two = browser.find_element_by_xpath("//input[@name='addressLine_2']")
    address_two.send_keys('address two')
    province = browser.find_element_by_xpath("//input[@name='district']")
    province.send_keys('district')
    postal = browser.find_element_by_xpath("//input[@name='postalCode']")
    postal.send_keys('58000')
    time.sleep(1)
    deposit_funds = browser.find_element_by_xpath(
        "//button[@class='Button_btn__JyuE1 Button_violet__5aLbL Button_withIcon__1TgpF Button_disable__0XBGJ']")
    deposit_funds.click()
    assert deposit_funds.is_displayed()
    time.sleep(1)
    browser.close()


def test_top_up_usdc_use_invalid_data_lost_city_field_empty():
    browser = driver
    browser.get(URL)
    input_chronicle_login = browser.find_element_by_xpath('//input[@name="login"]')
    input_chronicle_login.send_keys(USER_WITH_EMAIL_AND_KYC_VERIFICATION)
    time.sleep(1)
    input_chronicle_password = browser.find_element_by_xpath('//input[@name="password"]')
    input_chronicle_password.send_keys("213456qaZ")
    time.sleep(1)
    check_box = browser.find_element_by_xpath(
        "//div[@class='LoginForm_input__ZZfRr LoginForm_checkbox__KEUgt']//label[@class='Input_checkbox__cuH_e']")
    check_box.click()
    time.sleep(2)
    sign_in_button = browser.find_element_by_xpath(
        "//div[@class='LoginForm_button__tiE3C']//button[@type='button']")
    sign_in_button.click()
    time.sleep(3)
    pop_up_two_fa = browser.find_element_by_xpath(
        "//div[@class='Modal_modal__77o1K Modal_center__9TGY8 ']//div[@class='Modal_yellow__0RbLH']//button[@class='Button_btn__JyuE1 Button_transparent__FdLwD Button_withIcon__1TgpF']")
    pop_up_two_fa.click()
    time.sleep(2)
    user_drop = browser.find_element_by_xpath("//div[@class='UserHeaderCard_dropdownBtn__eXCOo']").click()
    time.sleep(1)
    manage_button = browser.find_element_by_xpath("//button[@class='Button_btn__JyuE1 Button_violet__5aLbL']").click()
    time.sleep(1)
    usdc_drop = browser.find_element_by_id('USDC').click()
    time.sleep(1)
    fiat = browser.find_element_by_id('Top_up_with_fiat').click()
    time.sleep(1)
    amount = browser.find_element_by_xpath("//input[@name='amount']")
    amount.send_keys('100')
    card_holder = browser.find_element_by_xpath("//input[@name='ccname']")
    card_holder.send_keys('clark kent')
    card_number = browser.find_element_by_xpath("//input[@name='cardnumber']")
    card_number.send_keys('42000000000000000')
    mm_yy = browser.find_element_by_xpath("//input[@name='expiry']")
    mm_yy.send_keys('1224')
    cvc = browser.find_element_by_xpath("//input[@name='cvc']")
    cvc.send_keys('123')
    country_drop = browser.find_element_by_xpath("//div[@class='CustomSelect_select__5EopE CustomSelect_crypto__mGhH3 CustomSelect_montserrat__L3McY']")
    country_drop.click()
    time.sleep(1)
    country = browser.find_elements_by_xpath("//div[@class='CustomSelect_option__x3Rbv']")
    country[0].click()
    city = browser.find_element_by_xpath("//input[@name='city']")
    city.send_keys('')
    address_one = browser.find_element_by_xpath("//input[@name='addressLine_1']")
    address_one.send_keys('address one')
    address_two = browser.find_element_by_xpath("//input[@name='addressLine_2']")
    address_two.send_keys('address two')
    province = browser.find_element_by_xpath("//input[@name='district']")
    province.send_keys('district')
    postal = browser.find_element_by_xpath("//input[@name='postalCode']")
    postal.send_keys('58000')
    time.sleep(1)
    error = browser.find_element_by_xpath("//div[@class='Input_tipError__CKiEf']").text
    assert error == 'Required'
    deposit_funds = browser.find_element_by_xpath(
        "//button[@class='Button_btn__JyuE1 Button_violet__5aLbL Button_withIcon__1TgpF Button_disable__0XBGJ']")
    deposit_funds.click()
    assert deposit_funds.is_displayed()
    time.sleep(1)
    browser.close()


def test_top_up_usdc_use_invalid_data_lost_address_field_empty():
    browser = driver
    browser.get(URL)
    input_chronicle_login = browser.find_element_by_xpath('//input[@name="login"]')
    input_chronicle_login.send_keys(USER_WITH_EMAIL_AND_KYC_VERIFICATION)
    time.sleep(1)
    input_chronicle_password = browser.find_element_by_xpath('//input[@name="password"]')
    input_chronicle_password.send_keys("213456qaZ")
    time.sleep(1)
    check_box = browser.find_element_by_xpath(
        "//div[@class='LoginForm_input__ZZfRr LoginForm_checkbox__KEUgt']//label[@class='Input_checkbox__cuH_e']")
    check_box.click()
    time.sleep(2)
    sign_in_button = browser.find_element_by_xpath(
        "//div[@class='LoginForm_button__tiE3C']//button[@type='button']")
    sign_in_button.click()
    time.sleep(3)
    pop_up_two_fa = browser.find_element_by_xpath(
        "//div[@class='Modal_modal__77o1K Modal_center__9TGY8 ']//div[@class='Modal_yellow__0RbLH']//button[@class='Button_btn__JyuE1 Button_transparent__FdLwD Button_withIcon__1TgpF']")
    pop_up_two_fa.click()
    time.sleep(2)
    user_drop = browser.find_element_by_xpath("//div[@class='UserHeaderCard_dropdownBtn__eXCOo']").click()
    time.sleep(1)
    manage_button = browser.find_element_by_xpath("//button[@class='Button_btn__JyuE1 Button_violet__5aLbL']").click()
    time.sleep(1)
    usdc_drop = browser.find_element_by_id('USDC').click()
    time.sleep(1)
    fiat = browser.find_element_by_id('Top_up_with_fiat').click()
    time.sleep(1)
    amount = browser.find_element_by_xpath("//input[@name='amount']")
    amount.send_keys('100')
    card_holder = browser.find_element_by_xpath("//input[@name='ccname']")
    card_holder.send_keys('clark kent')
    card_number = browser.find_element_by_xpath("//input[@name='cardnumber']")
    card_number.send_keys('42000000000000000')
    mm_yy = browser.find_element_by_xpath("//input[@name='expiry']")
    mm_yy.send_keys('1224')
    cvc = browser.find_element_by_xpath("//input[@name='cvc']")
    cvc.send_keys('123')
    country_drop = browser.find_element_by_xpath("//div[@class='CustomSelect_select__5EopE CustomSelect_crypto__mGhH3 CustomSelect_montserrat__L3McY']")
    country_drop.click()
    time.sleep(1)
    country = browser.find_elements_by_xpath("//div[@class='CustomSelect_option__x3Rbv']")
    country[0].click()
    city = browser.find_element_by_xpath("//input[@name='city']")
    city.send_keys('city')
    address_one = browser.find_element_by_xpath("//input[@name='addressLine_1']")
    address_one.send_keys('')
    address_two = browser.find_element_by_xpath("//input[@name='addressLine_2']")
    address_two.send_keys('address two')
    province = browser.find_element_by_xpath("//input[@name='district']")
    province.send_keys('district')
    postal = browser.find_element_by_xpath("//input[@name='postalCode']")
    postal.send_keys('58000')
    time.sleep(1)
    error = browser.find_element_by_xpath("//div[@class='Input_tipError__CKiEf']").text
    assert error == 'Required'
    deposit_funds = browser.find_element_by_xpath(
        "//button[@class='Button_btn__JyuE1 Button_violet__5aLbL Button_withIcon__1TgpF Button_disable__0XBGJ']")
    deposit_funds.click()
    assert deposit_funds.is_displayed()
    time.sleep(1)
    browser.close()


def test_top_up_usdc_use_invalid_data_lost_province_field_empty():
    browser = driver
    browser.get(URL)
    input_chronicle_login = browser.find_element_by_xpath('//input[@name="login"]')
    input_chronicle_login.send_keys(USER_WITH_EMAIL_AND_KYC_VERIFICATION)
    time.sleep(1)
    input_chronicle_password = browser.find_element_by_xpath('//input[@name="password"]')
    input_chronicle_password.send_keys("213456qaZ")
    time.sleep(1)
    check_box = browser.find_element_by_xpath(
        "//div[@class='LoginForm_input__ZZfRr LoginForm_checkbox__KEUgt']//label[@class='Input_checkbox__cuH_e']")
    check_box.click()
    time.sleep(2)
    sign_in_button = browser.find_element_by_xpath(
        "//div[@class='LoginForm_button__tiE3C']//button[@type='button']")
    sign_in_button.click()
    time.sleep(3)
    pop_up_two_fa = browser.find_element_by_xpath(
        "//div[@class='Modal_modal__77o1K Modal_center__9TGY8 ']//div[@class='Modal_yellow__0RbLH']//button[@class='Button_btn__JyuE1 Button_transparent__FdLwD Button_withIcon__1TgpF']")
    pop_up_two_fa.click()
    time.sleep(2)
    user_drop = browser.find_element_by_xpath("//div[@class='UserHeaderCard_dropdownBtn__eXCOo']").click()
    time.sleep(1)
    manage_button = browser.find_element_by_xpath("//button[@class='Button_btn__JyuE1 Button_violet__5aLbL']").click()
    time.sleep(1)
    usdc_drop = browser.find_element_by_id('USDC').click()
    time.sleep(1)
    fiat = browser.find_element_by_id('Top_up_with_fiat').click()
    time.sleep(1)
    amount = browser.find_element_by_xpath("//input[@name='amount']")
    amount.send_keys('100')
    card_holder = browser.find_element_by_xpath("//input[@name='ccname']")
    card_holder.send_keys('clark kent')
    card_number = browser.find_element_by_xpath("//input[@name='cardnumber']")
    card_number.send_keys('42000000000000000')
    mm_yy = browser.find_element_by_xpath("//input[@name='expiry']")
    mm_yy.send_keys('1224')
    cvc = browser.find_element_by_xpath("//input[@name='cvc']")
    cvc.send_keys('123')
    country_drop = browser.find_element_by_xpath("//div[@class='CustomSelect_select__5EopE CustomSelect_crypto__mGhH3 CustomSelect_montserrat__L3McY']")
    country_drop.click()
    time.sleep(1)
    country = browser.find_elements_by_xpath("//div[@class='CustomSelect_option__x3Rbv']")
    country[0].click()
    city = browser.find_element_by_xpath("//input[@name='city']")
    city.send_keys('city')
    address_one = browser.find_element_by_xpath("//input[@name='addressLine_1']")
    address_one.send_keys('address')
    address_two = browser.find_element_by_xpath("//input[@name='addressLine_2']")
    address_two.send_keys('address two')
    province = browser.find_element_by_xpath("//input[@name='district']")
    province.send_keys('')
    postal = browser.find_element_by_xpath("//input[@name='postalCode']")
    postal.send_keys('58000')
    time.sleep(1)
    error = browser.find_element_by_xpath("//div[@class='Input_tipError__CKiEf']").text
    assert error == 'Required'
    deposit_funds = browser.find_element_by_xpath(
        "//button[@class='Button_btn__JyuE1 Button_violet__5aLbL Button_withIcon__1TgpF Button_disable__0XBGJ']")
    deposit_funds.click()
    assert deposit_funds.is_displayed()
    time.sleep(1)
    browser.close()


def test_top_up_usdc_use_invalid_data_lost_postal_field_empty():
    browser = driver
    browser.get(URL)
    input_chronicle_login = browser.find_element_by_xpath('//input[@name="login"]')
    input_chronicle_login.send_keys(USER_WITH_EMAIL_AND_KYC_VERIFICATION)
    time.sleep(1)
    input_chronicle_password = browser.find_element_by_xpath('//input[@name="password"]')
    input_chronicle_password.send_keys("213456qaZ")
    time.sleep(1)
    check_box = browser.find_element_by_xpath(
        "//div[@class='LoginForm_input__ZZfRr LoginForm_checkbox__KEUgt']//label[@class='Input_checkbox__cuH_e']")
    check_box.click()
    time.sleep(2)
    sign_in_button = browser.find_element_by_xpath(
        "//div[@class='LoginForm_button__tiE3C']//button[@type='button']")
    sign_in_button.click()
    time.sleep(3)
    pop_up_two_fa = browser.find_element_by_xpath(
        "//div[@class='Modal_modal__77o1K Modal_center__9TGY8 ']//div[@class='Modal_yellow__0RbLH']//button[@class='Button_btn__JyuE1 Button_transparent__FdLwD Button_withIcon__1TgpF']")
    pop_up_two_fa.click()
    time.sleep(2)
    user_drop = browser.find_element_by_xpath("//div[@class='UserHeaderCard_dropdownBtn__eXCOo']").click()
    time.sleep(1)
    manage_button = browser.find_element_by_xpath("//button[@class='Button_btn__JyuE1 Button_violet__5aLbL']").click()
    time.sleep(1)
    usdc_drop = browser.find_element_by_id('USDC').click()
    time.sleep(1)
    fiat = browser.find_element_by_id('Top_up_with_fiat').click()
    time.sleep(1)
    amount = browser.find_element_by_xpath("//input[@name='amount']")
    amount.send_keys('100')
    card_holder = browser.find_element_by_xpath("//input[@name='ccname']")
    card_holder.send_keys('clark kent')
    card_number = browser.find_element_by_xpath("//input[@name='cardnumber']")
    card_number.send_keys('42000000000000000')
    mm_yy = browser.find_element_by_xpath("//input[@name='expiry']")
    mm_yy.send_keys('1224')
    cvc = browser.find_element_by_xpath("//input[@name='cvc']")
    cvc.send_keys('123')
    country_drop = browser.find_element_by_xpath("//div[@class='CustomSelect_select__5EopE CustomSelect_crypto__mGhH3 CustomSelect_montserrat__L3McY']")
    country_drop.click()
    time.sleep(1)
    country = browser.find_elements_by_xpath("//div[@class='CustomSelect_option__x3Rbv']")
    country[0].click()
    city = browser.find_element_by_xpath("//input[@name='city']")
    city.send_keys('city')
    address_one = browser.find_element_by_xpath("//input[@name='addressLine_1']")
    address_one.send_keys('address')
    address_two = browser.find_element_by_xpath("//input[@name='addressLine_2']")
    address_two.send_keys('address two')
    province = browser.find_element_by_xpath("//input[@name='district']")
    province.send_keys('district')
    postal = browser.find_element_by_xpath("//input[@name='postalCode']")
    postal.send_keys('')
    province.click()
    deposit_funds = browser.find_element_by_xpath(
        "//button[@class='Button_btn__JyuE1 Button_violet__5aLbL Button_withIcon__1TgpF Button_disable__0XBGJ']")
    deposit_funds.click()
    assert deposit_funds.is_displayed()
    time.sleep(1)
    error = browser.find_element_by_xpath("//div[@class='Input_tipError__CKiEf']").text
    assert error == 'Required'

    time.sleep(1)
    browser.close()